//STRICT CHECK I.E "===" , IT NOT JUST PERFORMS THE "==" FUNCTION BUT ALSO CHECKS THE DATATYPE

console.log("0" === 0)  //WILL GIVE FALSE CAUSE DIFFERENT DATATYPE
console.log("0" == 0)   // WILL GIVE TRUE CAUSE IT DONT CHECK DATATYPE

