// WHAT IS TEMPLATE LITERAL?

/*
TEMPLATE LITERAL IS A SPECIAL TYPE OF STRING THAT LETS USER CALL EMBEDDED EXPRESSIONS/VARIABLES USING 
"${}" IT IS EXPRESSED BY `` AND "NOT" BY SINGLE OR DOUBLE QUOTES.

KEY FEATURES - 

1) STRING INTERPOLATION I.E CALLING VARIABLES , EMBEDDED EXPRESSIONS DIRECTLY INTO A STRING USING "${}"

2) TEMPERAL LITERAL CAN WRITE "MULTILINE STRING" WITHOUT NEEDING "/n"
*/

let a = 3 , 
    b = ++a

console.log(`THE INCREMENT OF A I.E A : ${a}
THE INCREMENT OF B I.E B : ${b}`)

// THE ABOVE EXAMPLE SHOWS BOTH , ITS MULTILINE FEATURE AND IT BEING ABLE TO CALL VARIABLES.



