// IIFE [IMMEDIATELY INVOKED FUNCTION EXPRESSION]

// ALWAYS MAKE SURE TO USE ";" WHILE USING IIFE SO THAT IT WOULD KNOW WHERE TO STOP THE EXECUTION

// I.E EXECUTING FUNCTION RIGHT AWAY
 
function one(){                       // NAMED IIFE CAUSE IT HAS A NAME
    console.log('DB CONNECTED');
}

one()

// NOW TO IMMEDIATELY INVOKE FUNCTION , AS WE KNOW PREVIOUSLY "()" CREATES A BLOCK ITSELF SO TO EXECUTE , THE SYNTAX WOULD BE "(FUNCTION)(EXECUTION)"

console.log((function addTwo(num1 , num2) {
    return num1 + num2
})(3 , 4));    // WE PASS THE ARGUMENT IN THE EXECUTION BLOCK

// TO PRINT WE CAN JUST USE CONSOLE LOG AHEAD OF THE FUNTION BLOCK

/*
WHATS THE POINT OF IIFE AN WHY DO WE USE IIFE? [INTERVIEW QUESTION]

WE USE IIFE TO AVOID GLOBAL OBJECT INTEREFERENCE AS IT CREATES A BLOCK ELEMENT
*/

// USING ARROW FUNCTION  [UNNAMED IIFE]

console.log(((num1) => num1 * 2)(2));   

// TO WRITE 2 OR MORE IIFE'S , WE USE ";" WHICH AVOIDS ERRORS



